name: Daily Growfin Website Automation Testing Check # Automation name

on: # When to Run
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch: # run workflow manually

jobs: # What to do
  run-check: # customer jobs name
    runs-on: ubuntu-latest
    env:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      steps:
      - uses: actions/checkout@v4
      - name: Setup Puppeteer
        run: | # this for multi-line
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          npx ci
      - name: Run Growfin Peppeteer Check
        run: npx run check
